- package-lock.json
- package.json
- src/matter/ControllerNode.ts
- src/matter/IoBrokerNodeStorage.ts
- src/matter/clusters/OnOff.ts
This also includes upgrading all clusters and such to Matter 1.3
> update matter lib to 0.10.x and Add AsyncStorage

- src/main.ts
- src/matter/BaseServerNode.ts
- src/matter/BridgedDevicesNode.ts
- src/matter/ControllerNode.ts
- src/matter/DeviceNode.ts
make Controller configuration to be applied dynamically
> Dynamic Controller config handling

- .github/workflows/auto-approve.yml
- .github/workflows/create-release.yml
- .github/workflows/test-and-release.yml
with current branch protection settings
> added possibility to release versions

- src-admin/src/Tabs/Bridges.tsx
- src-admin/src/Tabs/BridgesAndDevices.tsx
- src-admin/src/Tabs/Controller.tsx
- src-admin/src/Tabs/Devices.tsx
- src-admin/src/Tabs/Options.tsx
- src-admin/src/Utils.tsx
- src-admin/src/components/ConfigHandler.tsx
- src-admin/src/i18n/de.json
- src-admin/src/i18n/en.json
- src-admin/src/i18n/es.json
- src-admin/src/i18n/fr.json
- src-admin/src/i18n/it.json
- src-admin/src/i18n/nl.json
- src-admin/src/i18n/pl.json
- src-admin/src/i18n/pt.json
- src-admin/src/i18n/ru.json
- src-admin/src/i18n/uk.json
- src-admin/src/i18n/zh-cn.json
- src-admin/tsconfig.json
> started working on devices design optimizations

- package-lock.json
- package.json
- src/matter/BaseServerNode.ts
- src/matter/ControllerNode.ts
> upgrade deps and fix reaccounce

- src/main.ts
this also prevents the factory reset issue
> Start nodes when activated

- package-lock.json
- package.json
- src/lib/devices/DeviceStateObject.ts
- src/lib/devices/GenericDevice.ts
- src/main.ts
- src/matter/BaseServerNode.ts
- src/matter/BridgedDevicesNode.ts
- src/matter/ControllerNode.ts
- src/matter/DeviceNode.ts
- test/devices.test.js
* Dep updates
* disabling devices on a bridge is not removing them anymore but really disabling them (aka unreachable) - for this unreachable state is also tweaked
* make sure ui updates get pushed when neeeded
* Small stuff here and there
> Optimizations for Device and Dep updates

- package-lock.json
- package.json
- src/matter/ControllerNode.ts
This is the first run over some Controller code in the adapter. The main work is not yet finished and will come after my vacation.
> First run for ControllerNode cleanup

- package-lock.json
- package.json
- src/matter/BridgedDevicesNode.ts
- src/matter/DeviceNode.ts
- src/matter/devices/MappingDimmer.ts
- src/matter/devices/MappingGenericElectricityDataDevice.ts
- src/matter/devices/MappingLight.ts
- src/matter/devices/MappingSocket.ts
- src/matter/devices/SharedStateHandlers.ts
This also maps the energy and power states that we provide into matter clusters
> Add Energy and Power clusters to Matter

- package-lock.json
- package.json
- src/lib/SubscribeManager.ts
- src/lib/devices/DeviceStateObject.ts
- src/main.ts
- src/matter/BaseServerNode.ts
- src/matter/BridgedDevicesNode.ts
- src/matter/ControllerNode.ts
- src/matter/DeviceNode.ts
- src/matter/GeneralMatterNode.ts
- src/matter/IoBrokerNodeStorage.ts
- src/matter/clusters/Base.ts
- src/matter/clusters/BooleanState.ts
- src/matter/clusters/Identify.ts
- src/matter/clusters/LevelControl.ts
- src/matter/clusters/OnOff.ts
- src/matter/from-matter/ioBrokerFactory.ts
- src/matter/to-matter/MappingDimmer.ts
- src/matter/to-matter/MappingGenericDevice.ts
- src/matter/to-matter/MappingGenericElectricityDataDevice.ts
- src/matter/to-matter/MappingHumidity.ts
- src/matter/to-matter/MappingLight.ts
- src/matter/to-matter/MappingSocket.ts
- src/matter/to-matter/MappingTemperature.ts
- src/matter/to-matter/SharedStateHandlers.ts
- src/matter/to-matter/matterFactory.ts
Oak, here is my first version, the status of last iobroker dev meeting ... but updated matter.js ... 
It includes:
* matter.js update to new package structure and latest controller version and asjustments needed for this
* some fixes on device side and code restructuring for classes (to-matter and from-matter to better see whats what)
* controller wise update to new structure and event driven matter.js solution
* generically parses application endpoint clusters into states already
* prepares next steps, but unfinished (map Matter devicetypes to iobroker devictypes)
> Controller revamp

- src/lib/DeviceManagement.ts
- src/main.ts
- src/matter/ControllerNode.ts
- src/matter/DeviceNode.ts
- src/matter/GeneralMatterNode.ts
- src/matter/to-iobroker/ContactSensorToIoBroker.ts
- src/matter/to-iobroker/DimmableToIobroker.ts
- src/matter/to-iobroker/DoorLockToIoBroker.ts
- src/matter/to-iobroker/GenericDeviceToIoBroker.ts
- src/matter/to-iobroker/GenericElectricityDataDeviceToIoBroker.ts
- src/matter/to-iobroker/HumiditySensorToIoBroker.ts
- src/matter/to-iobroker/OccupancyToIoBroker.ts
- src/matter/to-iobroker/OnOffLightToIoBroker.ts
- src/matter/to-iobroker/OnOffPlugInUnitToIoBroker.ts
- src/matter/to-iobroker/TemperatureSensorToIoBroker.ts
- src/matter/to-iobroker/UtilityOnlyToIoBroker.ts
- src/matter/to-iobroker/WaterLeakDetectorToIoBroker.ts
- src/matter/to-iobroker/ioBrokerFactory.ts
The PR:
* Add polling (incl interval config per node) of sttes - mainly energy states for now
* Add a Log button to later log debug content
* Catch some more matter.js errors and log them fully (because of nested error structures)
* Use Bridged device reachability info on bridged devices
* More optimizations
> Controller energy

- src-admin/package-lock.json
- src-admin/package.json
- src-admin/src/Tabs/Controller.tsx
- src-admin/src/Tabs/Options.tsx
> Used new admin-react version

- .github/workflows/create-release.yml
Hack for now, but should work. The "yes" command simply"presses enter" to all questions asked - which is mainly about the prerelease identifier
> Fix GHA release

- README.md
- io-package.json
- package-lock.json
- package.json
- src-admin/package.json
* IMPORTANT: Breaking change!! Please decommission ALL devices and do a full factory reset of the adapter Matter storage before installing this version. Pair the devices new afterwards.
* (@Apollon77) Finalizes Devices, Bridges and Controller functionality
* (@Apollon77) Upgrades to new Matter.js version and API (breaks storage structure)
* (@GermanBluefox) Moved build process of GUI to vite
* (@GermanBluefox) Added possibility to group devices in the GUI
> [OFFICIAL RELEASE] 0.2.0-alpha.0

- .github/workflows/create-release.yml
- README.md
- package-lock.json
- package.json
- src-admin/package-lock.json
- src/lib/devices/Ct.ts
- src/lib/devices/DeviceStateObject.ts
- src/lib/devices/GenericDevice.ts
- src/matter/BridgedDevicesNode.ts
- src/matter/DeviceNode.ts
- src/matter/to-matter/CtToMatter.ts
- src/matter/to-matter/GenericDeviceToMatter.ts
* (@Apollon77) Adds Color Temperature conversion if unit is "mireds"
* (@Apollon77) Fixes Color Temperature cluster initialization
* (@Apollon77) Fixes Min/Max calculation when unit conversion is used
fixes #163
> ColorTemperature fixes and Min/Max Unit Conversion

- README.md
- src-admin/package-lock.json
- src-admin/src/Tabs/BridgesAndDevices.tsx
- src/lib/devices/Door.ts
- src/lib/devices/FloodAlarm.ts
- src/lib/devices/Motion.ts
- src/lib/devices/Temperature.ts
- src/lib/devices/Window.ts
- src/main.ts
- src/matter/BaseServerNode.ts
- src/matter/to-matter/CtToMatter.ts
see commits, fixes #170 , fixes #171, fixes #169
> Several smaller fixes

- README.md
- src-admin/package-lock.json
- src/lib/DeviceFactory.ts
- src/lib/DeviceManagement.ts
- src/lib/devices/DeviceStateObject.ts
- src/main.ts
- src/matter/BridgedDevicesNode.ts
- src/matter/ControllerNode.ts
- src/matter/DeviceNode.ts
- src/matter/to-iobroker/GenericDeviceToIoBroker.ts
- src/matter/to-matter/matterFactory.ts
* (@Apollon77) Shows a progress indicator when deleting controller nodes
* (@Apollon77) Cuts names and labels to 32 or 64 characters as needed by Matter
* (@Apollon77) Improves error handling on devices and bridges
* (@Apollon77) Clear storage when removing a bridged device
* (@Apollon77) Processes changed objects with a 5s delay to prevent too many changes at once
* (@Apollon77) Fixes version determination
> Updates 04.12

- README.md
- io-package.json
- package-lock.json
- package.json
- src-admin/package.json
* (@Apollon77) Shows a progress indicator when deleting controller nodes%0A* (@Apollon77) Cuts names and labels to 32 or 64 characters as needed by Matter%0A* (@Apollon77) Improves error handling on devices and bridges%0A* (@Apollon77) Clear storage when removing a bridged device%0A* (@Apollon77) Processes changed objects with a 5s delay to prevent too many changes at once%0A* (@Apollon77) Fixes version determination%0A* (@Apollon77) Initializes Device objects more lazily
> [OFFICIAL RELEASE] 0.2.4

- README.md
- package-lock.json
- package.json
- src-admin/package-lock.json
- src-admin/src/Tabs/Bridges.tsx
- src-admin/src/Tabs/Devices.tsx
- src-admin/src/types.d.ts
- src/lib/DeviceManagement.ts
- src/lib/devices/DeviceStateObject.ts
- src/lib/devices/ElectricityDataDevice.ts
- src/lib/devices/GenericDevice.ts
- src/main.ts
- src/matter/DeviceNode.ts
- src/matter/GeneralMatterNode.ts
- src/matter/to-matter/CtToMatter.ts
- src/matter/to-matter/DimmerToMatter.ts
- src/matter/to-matter/GenericDeviceToMatter.ts
- src/matter/to-matter/GenericElectricityDataDeviceToMatter.ts
- src/matter/to-matter/LightToMatter.ts
- src/matter/to-matter/SocketToMatter.ts
* Sets the "no-compose" flag correctly to normally use composed if needed and adds it to a missing dialog
* Allows to use null values if needed
* Fixes UNREACH handling for devices
* Fixes object change handling for controller
* Allow Bridges to expose its name as a device name
* matter,js upgrade
Rest see commits
> Fixes and enhancements 06.12

- README.md
- io-package.json
- package-lock.json
- package.json
- src-admin/package-lock.json
- src-admin/package.json
* (@Apollon77) Fixes ColorTemperature light initialization because of matter.js update
> [OFFICIAL RELEASE] 0.2.6

- README.md
- io-package.json
- package-lock.json
- package.json
- src-admin/package.json
* (@Apollon77) Cleans up objects when a controller node is deleted%0A* (@Apollon77) Prevents controller configuration changes to be executed in parallel
> [OFFICIAL RELEASE] 0.2.7

- README.md
- io-package.json
- package-lock.json
- package.json
- src-admin/package.json
* BREAKING: Please re-enter your ioBroker Pro Cloud Password!%0A* (@Apollon77) Makes sure the adapter is stopped before being updated%0A* (@Apollon77) Optimizes device discovery and allows to stop it again
> [OFFICIAL RELEASE] 0.3.0

- README.md
- io-package.json
- package-lock.json
- package.json
- src-admin/package.json
* (@Apollon77) Fixes bridge/device icon display in UI%0A* (@Apollon77) Prevents displaying warning dialogs when nothing is wrong%0A* (@Apollon77) Adjusts some logs
> [OFFICIAL RELEASE] 0.3.1

- README.md
- io-package.json
- package-lock.json
- package.json
- src-admin/package.json
* (@Apollon77) Updates matter.js to address several issues%0A* (@bluefox) Optimized UI
> [OFFICIAL RELEASE] 0.3.4

- README.md
- package-lock.json
- package.json
- src/lib/DeviceManagement.ts
- src/lib/devices/Blind.ts
- src/lib/devices/BlindButtons.ts
- src/lib/devices/Cie.ts
- src/lib/devices/Ct.ts
- src/lib/devices/DeviceStateObject.ts
- src/lib/devices/GenericDevice.ts
- src/lib/devices/Hue.ts
- src/lib/devices/Thermostat.ts
- src/lib/devices/Volume.ts
- src/main.ts
- src/matter/ControllerNode.ts
- src/matter/GeneralMatterNode.ts
- src/matter/to-iobroker/ColorTemperatureLightToIoBroker.ts
- src/matter/to-iobroker/DimmableToIoBroker.ts
- src/matter/to-iobroker/ExtendedColorLightToIoBroker.ts
- src/matter/to-iobroker/GenericDeviceToIoBroker.ts
- src/matter/to-iobroker/GenericSwitchToIoBroker.ts
- src/matter/to-iobroker/SpeakerToIoBroker.ts
- src/matter/to-iobroker/ThermostatToIoBroker.ts
- src/matter/to-iobroker/WindowCoveringToIoBroker.ts
- src/matter/to-iobroker/ioBrokerFactory.ts
* Added possibility to enable/disable controlled nodes
* Added Information on battery and rssi for DM tile
* Added controller support for Color Lights, Speaker, Thermostats and Window coverings
* Optimized an fixed multiple things
> Enable/Disable and 4 new Controller device types

- README.md
- io-package.json
- package-lock.json
- package.json
- src-admin/package.json
* (@GermanBluefox) Fixed GUI errors%0A* (@GermanBluefox/@Apollon77) Added possibility to enable/disable controlled nodes%0A* (@Apollon77) Added Information on battery and rssi for DM tile%0A* (@Apollon77) Added controller support for Color Lights, Speaker, Thermostats and Window coverings%0A* (@Apollon77) Optimized an fixed multiple things
> [OFFICIAL RELEASE] 0.3.6

- README.md
- io-package.json
- package-lock.json
- package.json
- src-admin/package.json
* (@GermanBluefox) Showed the device name in paring dialog%0A* (@GermanBluefox/Apollon77) Adjusts connection type icons%0A* (@Apollon77) Optimized the discovery dialog handling%0A* (@Apollon77) Fixed Thermostat for Controller to update temperatures%0A* (@Apollon77) Gives Energy sensors a dedicated icon%0A* (@Apollon77) Optimized an fixed multiple things
> [OFFICIAL RELEASE] 0.3.7

- package-lock.json
- package.json
- src-admin/package-lock.json
- src-admin/src/App.tsx
- src-admin/src/Tabs/Controller.tsx
- src-admin/src/Tabs/Options.tsx
- src-admin/src/components/DiscoveredDevicesDialog.tsx
- Check if the device already added and do not allow to add it one more time
- Added default value for "Controller-Fabric-Label"
> Improvements for GUI

- README.md
- io-package.json
- package-lock.json
- package.json
- src-admin/package.json
* (@bluefox) Optimized UI%0A* (@Apollon77) Improved handling for Power Source cluster on root endpoint%0A* (@Apollon77) Changed Identify handling - Light will be turned on/off, others just logged
> [OFFICIAL RELEASE] 0.4.1

- README.md
- io-package.json
- package-lock.json
- package.json
- src-admin/package.json
* (@bluefox) Optimized UI%0A* (@Apollon77) Allows to turn light on/off via the dimming level as Zigbee adapter does%0A* (@Apollon77) Detects Switch changes via event which should be more reliable%0A* (@Apollon77) Optimizes some Node information
> [OFFICIAL RELEASE] 0.4.3

- src/lib/DeviceManagement.ts
- src/lib/i18n/de.json
- src/lib/i18n/en.json
- src/lib/i18n/es.json
- src/lib/i18n/fr.json
- src/lib/i18n/it.json
- src/lib/i18n/nl.json
- src/lib/i18n/pl.json
- src/lib/i18n/pt.json
- src/lib/i18n/ru.json
- src/lib/i18n/uk.json
- src/lib/i18n/zh-cn.json
changed label and translation for device identify time from 30s to 10s
> Changed time for device identify

- README.md
- io-package.json
- package-lock.json
- package.json
- src-admin/package-lock.json
- src-admin/package.json
* (@Apollon77) Added OPEN state for all Door Locks to open door again%0A* (@Apollon77) Fixed Thermostat initialization when no AUTO mode is supported%0A* (@Apollon77) Enhanced Enum state display in UI
> [OFFICIAL RELEASE] 0.4.4

- README.md
- io-package.json
- package-lock.json
- package.json
- src-admin/package.json
* (@Apollon77) Fixed Thermostat initialization logic and added more logging%0A* (@Apollon77) Fixed WindowCovering level to match ioBroker definition%0A* (@Apollon77) Updated matter.js for further optimizations
> [OFFICIAL RELEASE] 0.4.5

- README.md
- io-package.json
- package-lock.json
- package.json
- src-admin/package.json
* (@GermanBluefox) Optimized UI%0A* (@GermanBluefox) Added user feedback when device or bridged device is identified%0A* (@Apollon77) Fixes Thermostat logic for devices%0A* (@Apollon77) Ensures information are pushed to the UI when devices are in an error state
> [OFFICIAL RELEASE] 0.4.6

- README.md
- io-package.json
- package-lock.json
- package.json
- src-admin/package-lock.json
- src-admin/package.json
* (@Apollon77) Acknowledges Power states also on SET states%0A* (@Apollon77) Fixed Color Temperature handling for devices%0A* (@Apollon77) Fixed Thermostat setpoint logic
> [OFFICIAL RELEASE] 0.4.8

- README.md
- io-package.json
- package-lock.json
- package.json
- src-admin/package.json
* (@Apollon77) Enhanced error and invalid devices display for UI%0A* (@Apollon77) Fixed Button Press Controller support%0A* (@Apollon77) Added support to also select folders when adding devices%0A* (@Apollon77) Fixed Illuminance State type min/max
> [OFFICIAL RELEASE] 0.4.9

- README.md
- io-package.json
- package-lock.json
- package.json
- src-admin/package.json
* (@Apollon77) Fixed Thermostat limit initialization and Mode error%0A* (@Apollon77) Fixed Matter Event handling when mapped to an ioBroker state (e.g.GenericSwitch)%0A* (@Apollon77) Fixed Device type detection by really preferring the preferred type
> [OFFICIAL RELEASE] 0.4.10

- README.md
- io-package.json
- package-lock.json
- package.json
- src-admin/package.json
* (@Apollon77) Added support for Door state feature for Devices and Controllers%0A* (@Apollon77) Fixed Thermostat creation with Boost state
> [OFFICIAL RELEASE] 0.4.13

- README.md
- io-package.json
- package-lock.json
- package.json
- src-admin/package.json
* (@Apollon77) Improved stability and connection reliability (matter.js updated)%0A* (@Apollon77) Sort enum entries to improve detection quality when adding new devices
> [OFFICIAL RELEASE] 0.4.14

- README.md
- io-package.json
- package-lock.json
- package.json
- src-admin/package.json
* (@GermanBluefox) Added Button display and control in the UI%0A* (@Apollon77) Updates matter.js to optimize and add persisted subscriptions%0A* (@Apollon77) Fixed states-list initializations for controller states%0A* (@Apollon77) Fixed initialization issue when initial device connection for controller was not finished%0A* (@Apollon77) Adjusted connection display when reconnecting to a node to red in UI
> [OFFICIAL RELEASE] 0.4.15

- README.md
- io-package.json
- package-lock.json
- package.json
- src-admin/package.json
* IMPORTANT: Increase Node.js requirement to at least 20.x because else BLE currently does not work%0A* (@Apollon77) Added info log message when device decided for a different subscription interval
> [OFFICIAL RELEASE] 0.5.0

- README.md
- io-package.json
- package-lock.json
- package.json
- src-admin/package.json
* (@Apollon77) Updated matter.js to 0.15.4
> [OFFICIAL RELEASE] 0.5.3

- README.md
- io-package.json
- package-lock.json
- package.json
- src-admin/package.json
* (@Apollon77) Updated matter.js to 0.15.5
> [OFFICIAL RELEASE] 0.5.4
